In [1]:
from pymongo import MongoClient
from pymongo import GEOSPHERE
import pandas as pd
import requests
import json
from dotenv import load_dotenv
import os

In [2]:
client = MongoClient("localhost:27017")
db = client.get_database("ironhack")
companies = db.get_collection("companies")
offices = client.companies.offices

In [3]:
res = list(offices.find({},{"offices":1}))

In [4]:
query = {'$and': [{'funding_rounds.raised_amount' : {'$gt': 1000000}},
                  {"offices.country_code": 'ESP'}, {"offices.city": 'Madrid'}]}

In [5]:
selected_offices = list(offices.find(query,{"_id":0,'offices': 1, "name": 1}))

In [6]:
selected_offices

[{'name': 'Fon',
  'offices': {'description': '',
   'address1': 'Calle Quintanavides 15',
   'address2': '2-1',
   'zip_code': '28050',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.530724,
   'longitude': -3.632687}},
 {'name': 'eRepublik',
  'offices': {'description': 'Office',
   'address1': 'Almagro 22',
   'address2': '',
   'zip_code': '28010',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.43094,
   'longitude': -3.6952896}},
 {'name': 'Videoplaza',
  'offices': {'description': 'Madrid',
   'address1': 'Forum Business Center c/ Capitán Haya',
   'address2': '1 planta 15 Edificio Eurocentro',
   'zip_code': '28020',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4596242,
   'longitude': -3.6923285}},
 {'name': 'Busuu',
  'offices': {'description': '',
   'address1': 'Calle Columela 2, 1D',
   'address2': '',
   'zip_code': '28001',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4225487,
   'longitude': -3.6830316}},
 {'name': 'Nexway',
  'offices': {'description': 'Nexway Iberica',
   'address1': 'C/ Duque de FernÃ¡n NÃºÃ±ez NÂº2 2Âº Oficina 2',
   'address2': '',
   'zip_code': '28012',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4142986,
   'longitude': -3.7033074}},
 {'name': 'Comunitae',
  'offices': {'description': 'Headquarter',
   'address1': 'Calle Nuria 29',
   'address2': '',
   'zip_code': '28034',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4905109,
   'longitude': -3.7033403}},
 {'name': 'Tuenti Technologies',
  'offices': {'description': '',
   'address1': 'Plaza Cortes 2',
   'address2': '',
   'zip_code': '',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4158236,
   'longitude': -3.696277}},
 {'name': 'Virgin Play',
  'offices': {'description': 'Corporate Headquarters',
   'address1': 'Paseo de la Castellana, 9-11',
   'address2': '',
   'zip_code': '28046',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4273082,
   'longitude': -3.6895115}},
 {'name': 'ticketea',
  'offices': {'description': 'Office',
   'address1': 'Marques de Lema',
   'address2': '7',
   'zip_code': '28003',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4455155,
   'longitude': -3.7061764}},
 {'name': 'Genasys',
  'offices': {'description': '',
   'address1': 'C/ Ventura de la Vega 5',
   'address2': '28014 Madrid',
   'zip_code': '',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4161835,
   'longitude': -3.6988729}},
 {'name': 'BuyVIP',
  'offices': {'description': 'Office',
   'address1': '33. Edificio Atica 4 planta 2',
   'address2': '28224 Pozuelo de AlarcÃ³n',
   'zip_code': '',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4167413,
   'longitude': -3.7032498}},
 {'name': 'Fon',
  'offices': {'description': '',
   'address1': 'Calle Quintanavides 15',
   'address2': '2-1',
   'zip_code': '28050',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.530724,
   'longitude': -3.632687}},
 {'name': 'eRepublik',
  'offices': {'description': 'Office',
   'address1': 'Almagro 22',
   'address2': '',
   'zip_code': '28010',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.43094,
   'longitude': -3.6952896}},
 {'name': 'Videoplaza',
  'offices': {'description': 'Madrid',
   'address1': 'Forum Business Center c/ Capitán Haya',
   'address2': '1 planta 15 Edificio Eurocentro',
   'zip_code': '28020',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4596242,
   'longitude': -3.6923285}},
 {'name': 'Busuu',
  'offices': {'description': '',
   'address1': 'Calle Columela 2, 1D',
   'address2': '',
   'zip_code': '28001',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4225487,
   'longitude': -3.6830316}},
 {'name': 'Nexway',
  'offices': {'description': 'Nexway Iberica',
   'address1': 'C/ Duque de FernÃ¡n NÃºÃ±ez NÂº2 2Âº Oficina 2',
   'address2': '',
   'zip_code': '28012',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4142986,
   'longitude': -3.7033074}},
 {'name': 'Comunitae',
  'offices': {'description': 'Headquarter',
   'address1': 'Calle Nuria 29',
   'address2': '',
   'zip_code': '28034',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4905109,
   'longitude': -3.7033403}},
 {'name': 'Tuenti Technologies',
  'offices': {'description': '',
   'address1': 'Plaza Cortes 2',
   'address2': '',
   'zip_code': '',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4158236,
   'longitude': -3.696277}},
 {'name': 'Virgin Play',
  'offices': {'description': 'Corporate Headquarters',
   'address1': 'Paseo de la Castellana, 9-11',
   'address2': '',
   'zip_code': '28046',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4273082,
   'longitude': -3.6895115}},
 {'name': 'ticketea',
  'offices': {'description': 'Office',
   'address1': 'Marques de Lema',
   'address2': '7',
   'zip_code': '28003',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4455155,
   'longitude': -3.7061764}},
 {'name': 'Genasys',
  'offices': {'description': '',
   'address1': 'C/ Ventura de la Vega 5',
   'address2': '28014 Madrid',
   'zip_code': '',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4161835,
   'longitude': -3.6988729}},
 {'name': 'BuyVIP',
  'offices': {'description': 'Office',
   'address1': '33. Edificio Atica 4 planta 2',
   'address2': '28224 Pozuelo de AlarcÃ³n',
   'zip_code': '',
   'city': 'Madrid',
   'state_code': None,
   'country_code': 'ESP',
   'latitude': 40.4167413,
   'longitude': -3.7032498}}]

In [7]:
df_competency = pd.DataFrame(selected_offices)

In [8]:
df_competency

                   name                                            offices
0                   Fon  {'description': '', 'address1': 'Calle Quintan...
1             eRepublik  {'description': 'Office', 'address1': 'Almagro...
2            Videoplaza  {'description': 'Madrid', 'address1': 'Forum B...
3                 Busuu  {'description': '', 'address1': 'Calle Columel...
4                Nexway  {'description': 'Nexway Iberica', 'address1': ...
5             Comunitae  {'description': 'Headquarter', 'address1': 'Ca...
6   Tuenti Technologies  {'description': '', 'address1': 'Plaza Cortes ...
7           Virgin Play  {'description': 'Corporate Headquarters', 'add...
8              ticketea  {'description': 'Office', 'address1': 'Marques...
9               Genasys  {'description': '', 'address1': 'C/ Ventura de...
10               BuyVIP  {'description': 'Office', 'address1': '33. Edi...
11                  Fon  {'description': '', 'address1': 'Calle Quintan...
12            eRepublik  {'description': 'Office', 'address1': 'Almagro...
13           Videoplaza  {'description': 'Madrid', 'address1': 'Forum B...
14                Busuu  {'description': '', 'address1': 'Calle Columel...
15               Nexway  {'description': 'Nexway Iberica', 'address1': ...
16            Comunitae  {'description': 'Headquarter', 'address1': 'Ca...
17  Tuenti Technologies  {'description': '', 'address1': 'Plaza Cortes ...
18          Virgin Play  {'description': 'Corporate Headquarters', 'add...
19             ticketea  {'description': 'Office', 'address1': 'Marques...
20              Genasys  {'description': '', 'address1': 'C/ Ventura de...
21               BuyVIP  {'description': 'Office', 'address1': '33. Edi...

In [9]:
latitude = []
for x in range(0, len(df_competency)):
       latitude.append(df_competency.offices[x]['latitude'])

In [10]:
df_competency['latitude'] = pd.DataFrame(latitude)

In [11]:
longitude = []
for x in range(0, len(df_competency)):
       longitude.append(df_competency.offices[x]['longitude'])

In [12]:
df_competency['longitude'] = pd.DataFrame(longitude)

In [13]:
df_competency

,name,offices,latitude,longitude
0,Fon,"{'description': '', 'address1': 'Calle Quintan...",40.530724,-3.632687
1,eRepublik,"{'description': 'Office', 'address1': 'Almagro...",40.430940,-3.695290
2,Videoplaza,"{'description': 'Madrid', 'address1': 'Forum B...",40.459624,-3.692328
3,Busuu,"{'description': '', 'address1': 'Calle Columel...",40.422549,-3.683032
4,Nexway,"{'description': 'Nexway Iberica', 'address1': ...",40.414299,-3.703307
5,Comunitae,"{'description': 'Headquarter', 'address1': 'Ca...",40.490511,-3.703340
6,Tuenti Technologies,"{'description': '', 'address1': 'Plaza Cortes ...",40.415824,-3.696277
7,Virgin Play,"{'description': 'Corporate Headquarters', 'add...",40.427308,-3.689512
8,ticketea,"{'description': 'Office', 'address1': 'Marques...",40.445515,-3.706176
9,Genasys,"{'description': '', 'address1': 'C/ Ventura de...",40.416184,-3.698873
10,BuyVIP,"{'description': 'Office', 'address1': '33. Edi...",40.416741,-3.703250
11,Fon,"{'description': '', 'address1': 'Calle Quintan...",40.530724,-3.632687
12,eRepublik,"{'description': 'Office', 'address1': 'Almagro...",40.430940,-3.695290
13,Videoplaza,"{'description': 'Madrid', 'address1': 'Forum B...",40.459624,-3.692328
14,Busuu,"{'description': '', 'address1': 'Calle Columel...",40.422549,-3.683032
15,Nexway,"{'description': 'Nexway Iberica', 'address1': ...",40.414299,-3.703307
16,Comunitae,"{'description': 'Headquarter', 'address1': 'Ca...",40.490511,-3.703340
17,Tuenti Technologies,"{'description': '', 'address1': 'Plaza Cortes ...",40.415824,-3.696277
18,Virgin Play,"{'description': 'Corporate Headquarters', 'add...",40.427308,-3.689512
19,ticketea,"{'description': 'Office', 'address1': 'Marques...",40.445515,-3.706176
20,Genasys,"{'description': '', 'address1': 'C/ Ventura de...",40.416184,-3.698873
21,BuyVIP,"{'description': 'Office', 'address1': '33. Edi...",40.416741,-3.703250

In [14]:
df_competency = df_competency.drop(['offices'], axis=1)

In [15]:
df_competency

                   name   latitude  longitude
0                   Fon  40.530724  -3.632687
1             eRepublik  40.430940  -3.695290
2            Videoplaza  40.459624  -3.692328
3                 Busuu  40.422549  -3.683032
4                Nexway  40.414299  -3.703307
5             Comunitae  40.490511  -3.703340
6   Tuenti Technologies  40.415824  -3.696277
7           Virgin Play  40.427308  -3.689512
8              ticketea  40.445515  -3.706176
9               Genasys  40.416184  -3.698873
10               BuyVIP  40.416741  -3.703250
11                  Fon  40.530724  -3.632687
12            eRepublik  40.430940  -3.695290
13           Videoplaza  40.459624  -3.692328
14                Busuu  40.422549  -3.683032
15               Nexway  40.414299  -3.703307
16            Comunitae  40.490511  -3.703340
17  Tuenti Technologies  40.415824  -3.696277
18          Virgin Play  40.427308  -3.689512
19             ticketea  40.445515  -3.706176
20              Genasys  40.416184  -3.698873
21               BuyVIP  40.416741  -3.703250

In [16]:
df_competency.to_csv('data/competency.csv', index=False)